#
# DO NOT EDIT THIS FILE MANUALLY
# This makefile was automatically generate for IDE home directory
#
# Global OPTIONS file has been used in generation

# Main target
info:
	@echo  
	@echo  "  S3 IDE (Integrated Development Environment)"
	@echo     
	@echo  "  type:  make <target>"
	@echo  "  Possible <target>'s are: "
	@echo  "    make                 make IDE global Makefile" 
	@echo  "    allmake              make IDE Makefiles in each dir "
	@echo  "    clean                IDE total cleanup  "
	@echo  "    add                  launch a script to add a new pakage "
	@echo  "    <dir>_all            make all executable in <dir>   " 
	@echo  "    <dir>_loclib         make the local library in <dir>   " 
	@echo  "    <dir>_make           make the Makefile for <dir>   " 
	@echo  "    <dir>_allmake        make all the Makefiles for <dir> and its libs  "
	@echo  "    <dir>_clean          cleanup in <dir>  "
	@echo  "    <dir>_tar            tar of a single dir  "
	@echo  "    <dir>_alltar         tar of a dir with its libs "
	@echo    
	@echo  "  Possible <dir> values are: "     
	@echo  "    blas  " 
	@echo  "    fftw  " 
	@echo  "    iotk  " 
	@echo  "    numrec  " 
	@echo  "    ptk  " 
	@echo  "    lapack  " 
	@echo  "    ffti  " 
	@echo  "    lasi  " 
	@echo  "    sax  " 
	@echo   


# targets for libs handling

blas_all: 
	cd blas ; make all 
blas_loclib: 
	cd blas ; make loclib 
blas_make: 
	IDE/makemake.sh blas 
blas_allmake: blas_make 
	cd blas ; make allmake
blas_clean: 
	cd blas ; make clean 
blas_tar: 
	cd blas ; make tar 
blas_alltar: 
	cd blas ; make alltar 

fftw_all: 
	cd fftw ; make all 
fftw_loclib: 
	cd fftw ; make loclib 
fftw_make: 
	IDE/makemake.sh fftw 
fftw_allmake: fftw_make 
	cd fftw ; make allmake
fftw_clean: 
	cd fftw ; make clean 
fftw_tar: 
	cd fftw ; make tar 
fftw_alltar: 
	cd fftw ; make alltar 

iotk_all: 
	cd iotk ; make all 
iotk_loclib: 
	cd iotk ; make loclib 
iotk_make: 
	IDE/makemake.sh iotk 
iotk_allmake: iotk_make 
	cd iotk ; make allmake
iotk_clean: 
	cd iotk ; make clean 
iotk_tar: 
	cd iotk ; make tar 
iotk_alltar: 
	cd iotk ; make alltar 

numrec_all: 
	cd numrec ; make all 
numrec_loclib: 
	cd numrec ; make loclib 
numrec_make: 
	IDE/makemake.sh numrec 
numrec_allmake: numrec_make 
	cd numrec ; make allmake
numrec_clean: 
	cd numrec ; make clean 
numrec_tar: 
	cd numrec ; make tar 
numrec_alltar: 
	cd numrec ; make alltar 

ptk_all: 
	cd ptk ; make all 
ptk_loclib: 
	cd ptk ; make loclib 
ptk_make: 
	IDE/makemake.sh ptk 
ptk_allmake: ptk_make 
	cd ptk ; make allmake
ptk_clean: 
	cd ptk ; make clean 
ptk_tar: 
	cd ptk ; make tar 
ptk_alltar: 
	cd ptk ; make alltar 

lapack_all: 
	cd lapack ; make all 
lapack_loclib: 
	cd lapack ; make loclib 
lapack_make: 
	IDE/makemake.sh lapack 
lapack_allmake: lapack_make 
	cd lapack ; make allmake
lapack_clean: 
	cd lapack ; make clean 
lapack_tar: 
	cd lapack ; make tar 
lapack_alltar: 
	cd lapack ; make alltar 

ffti_all: 
	cd ffti ; make all 
ffti_loclib: 
	cd ffti ; make loclib 
ffti_make: 
	IDE/makemake.sh ffti 
ffti_allmake: ffti_make 
	cd ffti ; make allmake
ffti_clean: 
	cd ffti ; make clean 
ffti_tar: 
	cd ffti ; make tar 
ffti_alltar: 
	cd ffti ; make alltar 

lasi_all: 
	cd lasi ; make all 
lasi_loclib: 
	cd lasi ; make loclib 
lasi_make: 
	IDE/makemake.sh lasi 
lasi_allmake: lasi_make 
	cd lasi ; make allmake
lasi_clean: 
	cd lasi ; make clean 
lasi_tar: 
	cd lasi ; make tar 
lasi_alltar: 
	cd lasi ; make alltar 

sax_all: 
	cd sax ; make all 
sax_loclib: 
	cd sax ; make loclib 
sax_make: 
	IDE/makemake.sh sax 
sax_allmake: sax_make 
	cd sax ; make allmake
sax_clean: 
	cd sax ; make clean 
sax_tar: 
	cd sax ; make tar 
sax_alltar: 
	cd sax ; make alltar 


# make all Makefiles
allmake:  make 
	make -f Makefile allmake_
allmake_:
	IDE/makemake.sh blas
	IDE/makemake.sh fftw
	IDE/makemake.sh iotk
	IDE/makemake.sh numrec
	IDE/makemake.sh ptk
	IDE/makemake.sh lapack
	IDE/makemake.sh ffti
	IDE/makemake.sh lasi
	IDE/makemake.sh sax

# target for making Makefile
make: 
	IDE/IDE_makemake.sh 

# target to launch add_dir
add: 
	IDE/add_dir

# clean all
clean:  
	cd blas ; make clean_
	cd fftw ; make clean_
	cd iotk ; make clean_
	cd numrec ; make clean_
	cd ptk ; make clean_
	cd lapack ; make clean_
	cd ffti ; make clean_
	cd lasi ; make clean_
	cd sax ; make clean_
