!
!------------------------------------------------------------------------------!
! LASI Configuration File
!------------------------------------------------------------------------------!
! Here you can choose one of the preset configurations of the LASI lib.
! First you should set the values for the SINLGE and DOUBLE precision kinds,
! which are machine dependent. 
! Then select the interfaces you want to provide to the compiler just
! defining or leaving undefined selected macros.
! 
! The list of needed interfaces can be automatically be generated by the 
! script 
!   ../tools/which_lasi.sh
! 


!*******************
! SWAPPER TO LOCAL MACHINE DEFINITION
!  *******************
!
#ifdef __AIX
#   define __LASI_AIX
#endif
!
#ifdef __SGI
#   define __LASI_SGI
#endif
!
#ifdef __LINUX
#   define __LASI_LINUX
#endif



!*******************
! MACHINE DEPENDENT KINDS
!  *******************
!
! default
#define __LASI_KIND_SINGLE  selected_real_kind(6,30)
#define __LASI_KIND_DOUBLE  selected_real_kind(14,200)

#ifdef __LASI_AIX
#   undef __LASI_KIND_SINGLE
#   undef __LASI_KIND_DOUBLE
#   define __LASI_KIND_SINGLE  4
#   define __LASI_KIND_DOUBLE  8
#endif

#ifdef __LASI_SGI
#   undef __LASI_KIND_SINGLE
#   undef __LASI_KIND_DOUBLE
#   define __LASI_KIND_SINGLE  4
#   define __LASI_KIND_DOUBLE  8
#endif

#ifdef __LASI_LINUX
#   undef __LASI_KIND_SINGLE
#   undef __LASI_KIND_DOUBLE
#   define __LASI_KIND_SINGLE  4
#   define __LASI_KIND_DOUBLE  8
#endif


!***************************
! REQUIRED INTERFACES
!  ***************************
!
! BLAS
!
#define  __LASI_IAMAX lasi_IAMAX
#define  __LASI_NRM2 lasi_NRM2
#define  __LASI_ASUM lasi_ASUM
#define  __LASI_DOTU lasi_DOTU
#define  __LASI_DOTC lasi_DOTC
#define  __LASI_DOT lasi_DOT
#define  __LASI_DSDOT lasi_DSDOT
#define  __LASI_AXPY lasi_AXPY
#define  __LASI_COPY lasi_COPY
#define  __LASI_ROTG lasi_ROTG
#define  __LASI_ROT lasi_ROT
#define  __LASI_SCAL lasi_SCAL
#define  __LASI_SWAP lasi_SWAP
#define  __LASI_GBMV lasi_GBMV
#define  __LASI_GEMV lasi_GEMV
#define  __LASI_GERC lasi_GERC
#define  __LASI_GERU lasi_GERU
#define  __LASI_HBMV lasi_HBMV
#define  __LASI_HEMV lasi_HEMV
#define  __LASI_HER lasi_HER
#define  __LASI_HER2 lasi_HER2
#define  __LASI_HPR lasi_HPR
#define  __LASI_HPR2 lasi_HPR2
#define  __LASI_HPMV lasi_HPMV
#define  __LASI_TBMV lasi_TBMV
#define  __LASI_TPMV lasi_TPMV
#define  __LASI_TRMV lasi_TRMV
#define  __LASI_SYMV lasi_SYMV
#define  __LASI_SBMV lasi_SBMV
#define  __LASI_SPMV lasi_SPMV
#define  __LASI_TBSV lasi_TBSV
#define  __LASI_TPSV lasi_TPSV
#define  __LASI_TRSV lasi_TRSV
#define  __LASI_GER lasi_GER
#define  __LASI_SPR lasi_SPR
#define  __LASI_SPR2 lasi_SPR2
#define  __LASI_SYR lasi_SYR
#define  __LASI_SYR2 lasi_SYR2
#define  __LASI_GEMM lasi_GEMM
#define  __LASI_HEMM lasi_HEMM
#define  __LASI_HER2K lasi_HER2K
#define  __LASI_HERK lasi_HERK
#define  __LASI_SYMM lasi_SYMM
#define  __LASI_SYR2K lasi_SYR2K
#define  __LASI_SYRK lasi_SYRK
#define  __LASI_TRMM lasi_TRMM
#define  __LASI_TRSM lasi_TRSM
!
! LAPACK
!
#define  __LASI_LANGB lasi_LANGB
#define  __LASI_TGSEN lasi_TGSEN
#define  __LASI_TGSNA lasi_TGSNA
#define  __LASI_TGSYL lasi_TGSYL
#define  __LASI_TGEXC lasi_TGEXC
#define  __LASI_BDSDC lasi_BDSDC
#define  __LASI_STEGR lasi_STEGR
#define  __LASI_ORMRZ lasi_ORMRZ
#define  __LASI_UNMRZ lasi_UNMRZ
#define  __LASI_TZRZF lasi_TZRZF
#define  __LASI_GEQP3 lasi_GEQP3
#define  __LASI_GESDD lasi_GESDD
#define  __LASI_GGRQF lasi_GGRQF
#define  __LASI_GGQRF lasi_GGQRF
#define  __LASI_DISNA lasi_DISNA
#define  __LASI_TGSJA lasi_TGSJA
#define  __LASI_GGSVP lasi_GGSVP
#define  __LASI_TGEVC lasi_TGEVC
#define  __LASI_HGEQZ lasi_HGEQZ
#define  __LASI_GGBAK lasi_GGBAK
#define  __LASI_GGBAL lasi_GGBAL
#define  __LASI_GGHRD lasi_GGHRD
#define  __LASI_PBSTF lasi_PBSTF
#define  __LASI_SBGST lasi_SBGST
#define  __LASI_HBGST lasi_HBGST
#define  __LASI_SPGST lasi_SPGST
#define  __LASI_HPGST lasi_HPGST
#define  __LASI_BDSQR lasi_BDSQR
#define  __LASI_ORMBR lasi_ORMBR
#define  __LASI_UNMBR lasi_UNMBR
#define  __LASI_ORGBR lasi_ORGBR
#define  __LASI_UNGBR lasi_UNGBR
#define  __LASI_GBBRD lasi_GBBRD
#define  __LASI_GEBRD lasi_GEBRD
#define  __LASI_TRSEN lasi_TRSEN
#define  __LASI_TRSNA lasi_TRSNA
#define  __LASI_TRSYL lasi_TRSYL
#define  __LASI_TREXC lasi_TREXC
#define  __LASI_TREVC lasi_TREVC
#define  __LASI_HSEIN lasi_HSEIN
#define  __LASI_HSEQR lasi_HSEQR
#define  __LASI_ORMHR lasi_ORMHR
#define  __LASI_UNMHR lasi_UNMHR
#define  __LASI_ORGHR lasi_ORGHR
#define  __LASI_UNGHR lasi_UNGHR
#define  __LASI_GEBAK lasi_GEBAK
#define  __LASI_GEBAL lasi_GEBAL
#define  __LASI_GEHRD lasi_GEHRD
#define  __LASI_PTEQR lasi_PTEQR
#define  __LASI_STEIN lasi_STEIN
#define  __LASI_STEBZ lasi_STEBZ
#define  __LASI_STEDC lasi_STEDC
#define  __LASI_STERF lasi_STERF
#define  __LASI_STEQR lasi_STEQR
#define  __LASI_OPMTR lasi_OPMTR
#define  __LASI_UPMTR lasi_UPMTR
#define  __LASI_OPGTR lasi_OPGTR
#define  __LASI_UPGTR lasi_UPGTR
#define  __LASI_ORMTR lasi_ORMTR
#define  __LASI_UNMTR lasi_UNMTR
#define  __LASI_SBTRD lasi_SBTRD
#define  __LASI_HBTRD lasi_HBTRD
#define  __LASI_SPTRD lasi_SPTRD
#define  __LASI_HPTRD lasi_HPTRD
#define  __LASI_TZRQF lasi_TZRQF
#define  __LASI_ORMRQ lasi_ORMRQ
#define  __LASI_UNMRQ lasi_UNMRQ
#define  __LASI_ORGRQ lasi_ORGRQ
#define  __LASI_UNGRQ lasi_UNGRQ
#define  __LASI_GERQF lasi_GERQF
#define  __LASI_ORMQL lasi_ORMQL
#define  __LASI_UNMQL lasi_UNMQL
#define  __LASI_ORGQL lasi_ORGQL
#define  __LASI_UNGQL lasi_UNGQL
#define  __LASI_GEQLF lasi_GEQLF
#define  __LASI_ORMLQ lasi_ORMLQ
#define  __LASI_UNMLQ lasi_UNMLQ
#define  __LASI_ORGLQ lasi_ORGLQ
#define  __LASI_UNGLQ lasi_UNGLQ
#define  __LASI_GELQF lasi_GELQF
#define  __LASI_ORMQR lasi_ORMQR
#define  __LASI_UNMQR lasi_UNMQR
#define  __LASI_ORGQR lasi_ORGQR
#define  __LASI_UNGQR lasi_UNGQR
#define  __LASI_GEQRF lasi_GEQRF
#define  __LASI_GEQPF lasi_GEQPF
#define  __LASI_TBRFS lasi_TBRFS
#define  __LASI_TBCON lasi_TBCON
#define  __LASI_TBTRS lasi_TBTRS
#define  __LASI_TPTRI lasi_TPTRI
#define  __LASI_TPRFS lasi_TPRFS
#define  __LASI_TPCON lasi_TPCON
#define  __LASI_TPTRS lasi_TPTRS
#define  __LASI_TRTRI lasi_TRTRI
#define  __LASI_TRRFS lasi_TRRFS
#define  __LASI_TRCON lasi_TRCON
#define  __LASI_TRTRS lasi_TRTRS
#define  __LASI_SPTRI lasi_SPTRI
#define  __LASI_HPTRI lasi_HPTRI
#define  __LASI_SPRFS lasi_SPRFS
#define  __LASI_HPRFS lasi_HPRFS
#define  __LASI_HPCON lasi_HPCON
#define  __LASI_SPCON lasi_SPCON
#define  __LASI_SPTRS lasi_SPTRS
#define  __LASI_HPTRS lasi_HPTRS
#define  __LASI_HPTRF lasi_HPTRF
#define  __LASI_SPTRF lasi_SPTRF
#define  __LASI_SYTRI lasi_SYTRI
#define  __LASI_HETRI lasi_HETRI
#define  __LASI_SYRFS lasi_SYRFS
#define  __LASI_HERFS lasi_HERFS
#define  __LASI_SYCON lasi_SYCON
#define  __LASI_HECON lasi_HECON
#define  __LASI_HETRS lasi_HETRS
#define  __LASI_SYTRS lasi_SYTRS
#define  __LASI_HETRF lasi_HETRF
#define  __LASI_SYTRF lasi_SYTRF
#define  __LASI_PTRFS lasi_PTRFS
#define  __LASI_PTCON lasi_PTCON
#define  __LASI_PTTRS lasi_PTTRS
#define  __LASI_PTTRF lasi_PTTRF
#define  __LASI_PBEQU lasi_PBEQU
#define  __LASI_PBRFS lasi_PBRFS
#define  __LASI_PBCON lasi_PBCON
#define  __LASI_PBTRS lasi_PBTRS
#define  __LASI_PBTRF lasi_PBTRF
#define  __LASI_PPEQU lasi_PPEQU
#define  __LASI_PPTRI lasi_PPTRI
#define  __LASI_PPRFS lasi_PPRFS
#define  __LASI_PPCON lasi_PPCON
#define  __LASI_PPTRS lasi_PPTRS
#define  __LASI_PPTRF lasi_PPTRF
#define  __LASI_POEQU lasi_POEQU
#define  __LASI_POTRI lasi_POTRI
#define  __LASI_PORFS lasi_PORFS
#define  __LASI_POTRS lasi_POTRS
#define  __LASI_GTRFS lasi_GTRFS
#define  __LASI_GTCON lasi_GTCON
#define  __LASI_GTTRS lasi_GTTRS
#define  __LASI_GTTRF lasi_GTTRF
#define  __LASI_GBEQU lasi_GBEQU
#define  __LASI_GBRFS lasi_GBRFS
#define  __LASI_GBCON lasi_GBCON
#define  __LASI_GBTRS lasi_GBTRS
#define  __LASI_GBTRF lasi_GBTRF
#define  __LASI_GGSVD lasi_GGSVD
#define  __LASI_GEGV lasi_GEGV
#define  __LASI_GEGS lasi_GEGS
#define  __LASI_SBGVX lasi_SBGVX
#define  __LASI_HBGVX lasi_HBGVX
#define  __LASI_SBGVD lasi_SBGVD
#define  __LASI_HBGVD lasi_HBGVD
#define  __LASI_SBGV lasi_SBGV
#define  __LASI_HBGV lasi_HBGV
#define  __LASI_SPGVX lasi_SPGVX
#define  __LASI_HPGVX lasi_HPGVX
#define  __LASI_SPGVD lasi_SPGVD
#define  __LASI_HPGVD lasi_HPGVD
#define  __LASI_SPGV lasi_SPGV
#define  __LASI_HPGV lasi_HPGV
#define  __LASI_GESVD lasi_GESVD
#define  __LASI_GEEVX lasi_GEEVX
#define  __LASI_GGEVX lasi_GGEVX
#define  __LASI_GGEV lasi_GGEV
#define  __LASI_GEEV lasi_GEEV
#define  __LASI_GEESX lasi_GEESX
#define  __LASI_GGESX lasi_GGESX
#define  __LASI_GGES lasi_GGES
#define  __LASI_GEES lasi_GEES
#define  __LASI_STEVR lasi_STEVR
#define  __LASI_STEVX lasi_STEVX
#define  __LASI_STEVD lasi_STEVD
#define  __LASI_STEV lasi_STEV
#define  __LASI_SBEVX lasi_SBEVX
#define  __LASI_HBEVX lasi_HBEVX
#define  __LASI_SBEVD lasi_SBEVD
#define  __LASI_HBEVD lasi_HBEVD
#define  __LASI_SBEV lasi_SBEV
#define  __LASI_HBEV lasi_HBEV
#define  __LASI_SPEVX lasi_SPEVX
#define  __LASI_HPEVX lasi_HPEVX
#define  __LASI_SPEVD lasi_SPEVD
#define  __LASI_HPEVD lasi_HPEVD
#define  __LASI_SPEV lasi_SPEV
#define  __LASI_HPEV lasi_HPEV
#define  __LASI_GGGLM lasi_GGGLM
#define  __LASI_GGLSE lasi_GGLSE
#define  __LASI_GELSY lasi_GELSY
#define  __LASI_GELSD lasi_GELSD
#define  __LASI_GELSX lasi_GELSX
#define  __LASI_GELSS lasi_GELSS
#define  __LASI_GELS lasi_GELS
#define  __LASI_SPSV lasi_SPSV
#define  __LASI_HPSV lasi_HPSV
#define  __LASI_SYSV lasi_SYSV
#define  __LASI_HESV lasi_HESV
#define  __LASI_PTSV lasi_PTSV
#define  __LASI_PBSV lasi_PBSV
#define  __LASI_PPSV lasi_PPSV
#define  __LASI_POSV lasi_POSV
#define  __LASI_GTSV lasi_GTSV
#define  __LASI_GBSV lasi_GBSV
#define  __LASI_GESV lasi_GESV
#define  __LASI_SPSVX lasi_SPSVX
#define  __LASI_HPSVX lasi_HPSVX
#define  __LASI_SYSVX lasi_SYSVX
#define  __LASI_HESVX lasi_HESVX
#define  __LASI_PTSVX lasi_PTSVX
#define  __LASI_PBSVX lasi_PBSVX
#define  __LASI_PPSVX lasi_PPSVX
#define  __LASI_POSVX lasi_POSVX
#define  __LASI_GTSVX lasi_GTSVX
#define  __LASI_GBSVX lasi_GBSVX
#define  __LASI_GESVX lasi_GESVX
#define  __LASI_GETRF lasi_GETRF
#define  __LASI_GETRS lasi_GETRS
#define  __LASI_GETRI lasi_GETRI
#define  __LASI_GERFS lasi_GERFS
#define  __LASI_GEEQU lasi_GEEQU
#define  __LASI_LANGE lasi_LANGE
#define  __LASI_GECON lasi_GECON
#define  __LASI_SYEV lasi_SYEV
#define  __LASI_HEEV lasi_HEEV
#define  __LASI_SYEVD lasi_SYEVD
#define  __LASI_HEEVD lasi_HEEVD
#define  __LASI_SYEVR lasi_SYEVR
#define  __LASI_HEEVR lasi_HEEVR
#define  __LASI_SYEVX lasi_SYEVX
#define  __LASI_HEEVX lasi_HEEVX
#define  __LASI_SYGST lasi_SYGST
#define  __LASI_HEGST lasi_HEGST
#define  __LASI_SYGV lasi_SYGV
#define  __LASI_HEGV lasi_HEGV
#define  __LASI_SYGVX lasi_SYGVX
#define  __LASI_HEGVX lasi_HEGVX
#define  __LASI_SYGVD lasi_SYGVD
#define  __LASI_HEGVD lasi_HEGVD
#define  __LASI_SYTRD lasi_SYTRD
#define  __LASI_HETRD lasi_HETRD
#define  __LASI_ORGTR lasi_ORGTR
#define  __LASI_UNGTR lasi_UNGTR
#define  __LASI_LANSY lasi_LANSY
#define  __LASI_POTRF lasi_POTRF
#define  __LASI_POCON lasi_POCON
#define  __LASI_ILAENV lasi_ILAENV
#define  __LASI_LAGGE lasi_LAGGE
#define  __LASI_LAMCH lasi_LAMCH
