info:
	cd src ; make info

all:
	cd src ; make all

loclib:
	cd src ; make loclib

loclib_only:
	cd src ; make loclib_only

ide_internal:
	cd src ; make ide_internal

ide_external:
	cd src ; make ide_external

fake_external.a:
	cd src ; make fake_external.a

libblas.a:
	cd src ; make libblas.a

libs:
	cd src ; make libs

make:
	cd src ; make make

allmake:
	cd src ; make allmake

clean_:
	cd src ; make clean_

clean:
	cd src ; make clean

tarlist:
	cd src ; make tarlist

tar:
	cd src ; make tar

alltar:
	cd src ; make alltar

print_info:
	cd src ; make print_info

